# Generated by Django 6.0.1 on 2026-02-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bedroom',
            fields=[
                ('room_number', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Nro. de la Habitacion')),
                ('bedrooms_number', models.PositiveIntegerField()),
                ('bathroom_number', models.PositiveIntegerField()),
                ('room_price', models.FloatField()),
                ('room_availability', models.CharField()),
            ],
        ),
    ]
