# Generated by Django 6.0.1 on 2026-02-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='room_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='room_availability',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='room_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
