# Generated by Django 6.0.1 on 2026-02-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakeReservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField()),
                ('person_number', models.IntegerField()),
                ('date_entrance', models.DateField()),
                ('date_exit', models.DateField()),
                ('hour_entrance', models.TimeField()),
                ('hour_exit', models.TimeField()),
                ('total_price', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
    ]
