# Generated by Django 6.0.1 on 2026-02-01 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedrooms', '0002_bedroom_room_type_alter_bedroom_room_availability_and_more'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makereservation',
            name='reservation_id',
        ),
        migrations.AddField(
            model_name='makereservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='makereservation',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bedrooms.bedroom'),
        ),
        migrations.AlterField(
            model_name='makereservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
